title: "krwill.xyz"
url: "https://krwill.xyz"
description: "Artist and maker. Five doors: Shop, Life, Notes, Photos, Professional."
social_image: /assets/social-card.svg
theme: minima
plugins: [jekyll-seo-tag]
permalink: /blog/:year/:month/:day/:title/
